apiVersion: v1
kind: Pod
metadata:
  name: with-nodeaffinity
spec:
  containers:
    - name: app
      image: nginx:1.27
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - minikube
